### ISSUE TITLE
Accordion component

### ISSUE THREAD

**Issue by gjones** [ClickHouse/click-ui#22]
### Summary 
We need a basic accordion component for Click UI. We should give it three sizes `small`, `medium`, and `large` and the states `default` (collapsed), `hover`, and `active` (expanded).

See [Figma](https://www.figma.com/file/mjSci5n5YREyVlvaVjMSDq/Click-UI-Library?type=design&node-id=2276%3A9543&t=D2yb5A7K9eJCK68D-1).

<img width="802" alt="CleanShot 2023-06-08 at 16 36 23@2x" src="https://github.com/ClickHouse/click-ui/assets/305167/c86a8b27-dc2c-451c-867b-e581f03bca8f">

### Tokens provided: 

```
  --click-accordion-color-label-active: var(--click-global-color-text-default);
  --click-accordion-color-label-hover: lch(13.9 1.33 305);
  --click-accordion-color-label-default: var(--click-global-color-text-default);
  --click-accordion-large-typography-label-active: var(--typography-styles-text-lg);
  --click-accordion-large-typography-label-default: var(--typography-styles-text-lg);
  --click-accordion-large-space-gap: var(--spaces-1);
  --click-accordion-large-icon-size-width: var(--click-image-large-size-width);
  --click-accordion-large-icon-size-height: var(--click-image-large-size-height);
  --click-accordion-medium-typography-label-active: var(--typography-styles-text-md);
  --click-accordion-medium-typography-label-default: var(--typography-styles-text-md);
  --click-accordion-medium-space-gap: var(--spaces-1);
  --click-accordion-medium-icon-size-width: var(--click-image-medium-size-width);
  --click-accordion-medium-icon-size-height: var(--click-image-medium-size-height);
  --click-accordion-small-typography-label-active: var(--typography-styles-text-sm);
  --click-accordion-small-typography-label-default: var(--typography-styles-text-sm);
  --click-accordion-small-space-gap: var(--spaces-1);
  --click-accordion-small-icon-size-width: var(--click-image-small-size-width);
  --click-accordion-small-icon-size-height: var(--click-image-small-size-height);
  ```

**Comment by serdec** [comment]
@gjones it seems the accordion colors are missing from the dark theme

**Comment by gjones** [comment]
@serdec Is that causing a problem? The way it works in Figma is that if its not set it just uses the light theme version. In this case because `--click-accordion-color-label-active: var(--click-global-color-text-default);` and text-default automatically switches to white in dark mode, it would simply inherit that value, is this not the case? I can easily create tokens if necessary.

**Comment by serdec** [comment]
http://localhost:6006/?path=/story/accordion--default&globals=theme:light

<img width="212" alt="image" src="https://github.com/ClickHouse/click-ui/assets/1456541/8860ce85-e835-4e05-82b5-059c464816f4">

http://localhost:6006/?path=/story/accordion--default&globals=theme:dark

<img width="186" alt="image" src="https://github.com/ClickHouse/click-ui/assets/1456541/08da55f7-6490-4a49-af00-f09f29be2331">

the color falls back to the light one, but on a black background is not visible

**Comment by gjones** [comment]
I'll add the dark mode tokens today.
