### ISSUE TITLE
Option to disable "visited" decoration for the Link component without extra styles

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/click-ui#278]
On some pages, it is necessary to keep all links "unvisited" to increase the visibility/readability of the link text.

![image](https://github.com/ClickHouse/click-ui/assets/3175289/7268a38f-cc03-46a5-a047-300bff44666a)
See that the "examples" link is not very distinguishable from the rest of the text. Ideally, we should be able to prevent that without adding an extra `style` for the `Link` component.

In addition, currently, it's inconsistent: after the first click, it is "visited"; after the second - it is "not visited" again (at least on the latest FF).

**Comment by gjones** [comment]
Yeah there's an issue I've been working through where the sql console has `color:inherit` set globally which overrides the visited state. This should have been addressed by this PR https://github.com/ClickHouse/click-ui/pull/264, but I'm not sure if it's  made its way to production yet.

**Comment by gjones** [comment]
This has been fixed by a couple of separate PRs so closing.

![CleanShot 2024-01-04 at 07 27 32@2x](https://github.com/ClickHouse/click-ui/assets/305167/4762d0ab-ba55-44a0-8ac7-d230d520ba99)
