### ISSUE TITLE
Date/Time Picker Component

### ISSUE THREAD

**Issue by pjhampton** [ClickHouse/click-ui#326]
Some upcoming work will require us to take date/times and date/time ranges from users when creating batch / streaming ClickPipes. 

We can start with plain text boxes on our end so it's not urgent, but I believe it would enhance the user experience and require less involved input validation in the backend.

- [x] Basic `DatePicker` component
  - Tests
  - Stories
- [ ] `DateRangePicker` component
   - Tests
  - Stories
- [ ] `DateTimePicker` component
  - Tests
  - Stories

**Comment by gjones** [comment]
This is on the design roadmap

**Comment by crisalbu** [comment]
Hi @pjhampton , I have some designs for the `date picker`.


### Simple Date Picker
Users select a single date. 

<img width="1472" alt="Screenshot 2024-06-27 at 13 37 26" src="https://github.com/ClickHouse/click-ui/assets/39407524/ffa7c8dc-5ac5-4c80-a6bc-a3ffca429200">

### Simple Date Range

Users can select an interval between 2 dates. We can also disable future dates if we want. 

<img width="1358" alt="Screenshot 2024-06-27 at 13 38 08" src="https://github.com/ClickHouse/click-ui/assets/39407524/0f224cff-48c5-488f-9f00-1c8a62d8f887">

### Date Range with Predefined Values
To simplify date range selection, we can offer some predefined values, like `Past day`, `Past week` `Past 2 weeks`, `Past month`, etc, and if those are not enough, we can let users select their own custom period of time. 

<img width="1274" alt="Screenshot 2024-06-27 at 13 37 50" src="https://github.com/ClickHouse/click-ui/assets/39407524/fc83eeb7-1b4d-4dba-84d4-68e33a9210c5">

Do these solve your use cases, Pete?

**Comment by crisalbu** [comment]
### [Designs can be found here](https://www.figma.com/design/mjSci5n5YREyVlvaVjMSDq/Click-UI-Library?node-id=8493-1034&t=sEmpTMUEgbwx1uHU-1)

@serdec, can we plan an implementation in the near future?

**Comment by serdec** [comment]
@crisalbu we don't have the bandwidth at the moment to take on this task

**Comment by hoorayimhelping** [comment]
@vineethasok and I chatted about and this and he proposed a list of libraries we can use to power this.

- [Ant design](https://ant.design/components/date-picker). Pros: Lots of functionality, highly active and used library. Cons: may not be very customizable, comes with a whole design library
- [react-multi-date-picker](https://shahabyazdi.github.io/react-multi-date-picker/). Pros: Provides the functionality we need, looks pretty easy to use. Cons: is large (~370 kB package size), unclear how performant this is, seems to be a single person maintaining this project.
- [Adobe react-spectrum datepicker](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html): Pros: Extensible, maintained by Adobe. Cons: will probably require more work than the first two libraries, maintained by Adobe.
- [h6s calendar](https://h6s.dev/docs/calendar): Pros: extensible, lightweight. Cons: requires us to implement the UI

**Comment by serdec** [comment]
@hoorayimhelping how did we decide to move forward?

**Comment by hoorayimhelping** [comment]
@serdec haven't made a decision yet. Do you have any preferences on a library?

**Comment by serdec** [comment]
@hoorayimhelping i only used ant design previously, but my experience wasn't really good as as you stated it wasn't really customizable. 

I'll trust your judgment, i also know that airbnb have an open source date-picker just fyi

**Comment by hoorayimhelping** [comment]
I've made good progress on the basic DatePicker. What I'm thinking is that I'll get the basic `DatePicker` in first, so that if anyone needs one, they can start using it, and then I'll start working on a `DateRangePicker`.

I'll get a PR up for it in the next couple of days, I need to do some more polishing and add tests.


![Screenshot 2024-10-15 at 9 22 33 AM](https://github.com/user-attachments/assets/b0409bcf-1db6-4b02-b539-b4003ff1f7c9)
![Screenshot 2024-10-15 at 9 22 54 AM](https://github.com/user-attachments/assets/4d61b691-adc2-406c-aa79-0cbe655dbb52)

**Comment by serdec** [comment]
looks great!

**Comment by gjones** [comment]
Closing as completed. 🎉
