### ISSUE TITLE
move Select to top-level folder

### ISSUE THREAD

**Issue by serdec** [ClickHouse/click-ui#83]
Let's move the Select component to the top-level folder to keep our repo structure consistent

**Comment by vineethasok** [comment]
@serdec @guykoh @fneves @gjones 
I believe all the form elements should reside inside the FormField Folder like Checkbox, RadioButton , select and input
This way we can filter the filter elements with other components
I wish to know your thoughts

**Comment by fneves** [comment]
how do we currently export / import those components vs the others?

**Comment by serdec** [comment]
i think all these elements can exist outside of a form and on their own. For isntance a checkbox can appear in a table column, as well as an input can appear practically anywhere. 

For me it makes more sense to have all of them at the top level together with the other components

**Comment by gjones** [comment]
I tend to side on breaking the components into logical groupings/sections to help with discovery and order. That said, we don't have that many components yet so if you feel strongly about a flat structure I'm not going to argue - and I'll try not to be too smug in a years time when the flat structure becomes unwieldy and we have to figure out how to group these again, ha.

**Comment by serdec** [comment]
i think a flat structure is actually very scalable in terms of development, so i would argue in favor of that. Maybe we can consider a different approach for documentation

**Comment by gjones** [comment]
> i think a flat structure is actually very scalable in terms of development

Totally agree, sorry, I thought you were talking about the sidenav in the storybook. Either way, I'm fine with flat approach.

**Comment by fneves** [comment]
lets go with flat. I don't have a strong opinion on any of them.
